language: python
python:
- 3.4
- 3.5
install: pip install tox coveralls
script: tox
after_success:
- coveralls
notifications:
  slack:
    secure: XZ9C7sBBWsCBKWZY2nDBkaCaePqbb3ham+FLtXTiaRCq+rfl5Q3Effm91YvKmT2i/7rqXjgDb8moVA9NEBF1SLsZlMMVdvY7BIDwf21m26Nm/a3Z0VdTxexAUp4N6O6SqRVua+XcDuYvEWBpDAksiLlbHlI+Z1aQiEHvQx0UqW0=
