name: py35
dependencies:
- pip=8.1.2
- pip:
  - alabaster==0.7.9
  - arrow==0.8.0
  - blinker==1.4
  - boto3==1.4.1
  - coverage==4.2
  - declare==0.9.11
  - flake8==3.0.4
  - pytest==3.0.3
  - Sphinx==1.4.8
  - sphinx_rtd_theme==0.1.9
  - tox==2.4.1
